package com.dbook.domain.common.access

enum class Permission {
    ADMIN_PORTAL_ACCESS,
    CUSTOMER_READ,
    CUSTOMER_NOTE,
    CUSTOMER_BLOCK,
    CUSTOMER_EXPORT,
    CUSTOMER_ERASE,
    BOOKING_READ_ANY,
    BOOKING_CANCEL_ANY,
    PAYMENT_REFUND,
    FLIGHT_READ,
    FLIGHT_WRITE,
    CATALOG_WRITE,
    PROMO_WRITE,
    REVIEW_MODERATE,
    DASHBOARD_READ,
    AUDIT_READ,
    ADMIN_MANAGE,
}
