spring:
  application:
    name: dbook
  datasource:
    url: jdbc:postgresql://localhost:5432/dbook
    username: dbook
    password: dbook
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
server:
  port: 8080
