variable "name" {
  description = "Name prefix for RDS resources."
  type        = string
}

variable "vpc_id" {
  type = string
}

variable "private_subnet_ids" {
  description = "Subnets the DB subnet group spans — must be private (no direct internet route)."
  type        = list(string)
}

variable "allowed_security_group_id" {
  description = "Security group (e.g. the ECS service's) allowed to reach the database on the Postgres port."
  type        = string
}

variable "db_name" {
  type    = string
  default = "dbook"
}

variable "db_username" {
  type    = string
  default = "dbook"
}

variable "db_password" {
  description = "Generated by the root module (random_password) and shared with the secrets module — never hardcoded here."
  type        = string
  sensitive   = true
}

variable "instance_class" {
  description = "Smallest practical instance for a learning workload."
  type        = string
  default     = "db.t4g.micro"
}
