variable "name" {
  description = "Name prefix for the secrets."
  type        = string
}

variable "db_password" {
  description = "Same password given to the RDS module — stored here so ECS can inject it without it ever appearing in a Task Definition in plaintext."
  type        = string
  sensitive   = true
}

variable "jwt_secret" {
  description = "Signing key for JWT access/refresh tokens. Generated once by the root module (random_password), never hardcoded."
  type        = string
  sensitive   = true
}

variable "bootstrap_admin_password" {
  description = "Password of the first SUPER_ADMIN (BootstrapSuperAdminRunner creates it only while none exists). Generated by the root module; rotate it after the first sign-in."
  type        = string
  sensitive   = true
}

variable "totp_encryption_key" {
  description = "Key that will encrypt the 2FA (TOTP) secrets of the team at rest (M29). Generated by the root module; stored now so the key exists before the feature does."
  type        = string
  sensitive   = true
}
