package com.dbook.domain.audit

enum class AuditAction(val target: String) {
    FLIGHT_CREATED("FLIGHT"),
    BOOKING_CANCELLED_BY_STAFF("BOOKING"),
    ACCESS_DENIED("ENDPOINT"),
    STAFF_INVITED("INVITATION"),
    STAFF_INVITATION_RESENT("INVITATION"),
    STAFF_INVITATION_REVOKED("INVITATION"),
    STAFF_INVITATION_ACCEPTED("INVITATION"),
    STAFF_ROLE_CHANGED("STAFF"),
    STAFF_BLOCKED("STAFF"),
    STAFF_UNBLOCKED("STAFF"),
}
